# action.yml
name: 'setup-cloudflared-ssh-proxy'
description: 'Setup cloudflared tunnel proxy, inside github actions'
inputs:
  CF_CLIENT_ID:  # id of input
    description: 'Cloudflare access tunnel, service token id'
    required: true
    default: 'default'
  CF_CLIENT_SECRET:  # id of input
    description: 'Cloudflare access tunnel, service token secret'
    required: true
    default: 'default'
  HOST:  # id of input
    description: 'Cloudflare access tunnel, associated application domain'
    required: true
    default: '0.0.0.0'
# outputs:
#   output: # id of output
#     description: 'the output of the command'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.HOST }}
    - ${{ inputs.CF_CLIENT_ID }}
    - ${{ inputs.CF_CLIENT_SECRET }}
